# MQTT Keys
MQTT_BROKER = "broker"
MQTT_TOPIC = "topic"
MQTT_QOS = "qos"
MQTT_USERNAME = "username"
MQTT_PASSWORD = "password"
MQTT_RECONNECT_INTERVAL = "reconnect_interval"
MQTT_KEEP_ALIVE_INTERVAL = "keep_alive_interval"
MQTT_QUEUE_DIR = "queue_dir"
MQTT_QUEUE_LIMIT = "queue_limit"

# A list of all valid configuration keys for an MQTT target.
NOTIFY_MQTT_KEYS = [
    "enable",  # "enable" is a common key
    MQTT_BROKER,
    MQTT_TOPIC,
    MQTT_QOS,
    MQTT_USERNAME,
    MQTT_PASSWORD,
    MQTT_RECONNECT_INTERVAL,
    MQTT_KEEP_ALIVE_INTERVAL,
    MQTT_QUEUE_DIR,
    MQTT_QUEUE_LIMIT,
    "comment",
]

# MQTT Environment Variables
ENV_MQTT_ENABLE = "RUSTFS_NOTIFY_MQTT_ENABLE"
ENV_MQTT_BROKER = "RUSTFS_NOTIFY_MQTT_BROKER"
ENV_MQTT_TOPIC = "RUSTFS_NOTIFY_MQTT_TOPIC"
ENV_MQTT_QOS = "RUSTFS_NOTIFY_MQTT_QOS"
ENV_MQTT_USERNAME = "RUSTFS_NOTIFY_MQTT_USERNAME"
ENV_MQTT_PASSWORD = "RUSTFS_NOTIFY_MQTT_PASSWORD"
ENV_MQTT_RECONNECT_INTERVAL = "RUSTFS_NOTIFY_MQTT_RECONNECT_INTERVAL"
ENV_MQTT_KEEP_ALIVE_INTERVAL = "RUSTFS_NOTIFY_MQTT_KEEP_ALIVE_INTERVAL"
ENV_MQTT_QUEUE_DIR = "RUSTFS_NOTIFY_MQTT_QUEUE_DIR"
ENV_MQTT_QUEUE_LIMIT = "RUSTFS_NOTIFY_MQTT_QUEUE_LIMIT"

ENV_NOTIFY_MQTT_KEYS = [
    ENV_MQTT_ENABLE,
    ENV_MQTT_BROKER,
    ENV_MQTT_TOPIC,
    ENV_MQTT_QOS,
    ENV_MQTT_USERNAME,
    ENV_MQTT_PASSWORD,
    ENV_MQTT_RECONNECT_INTERVAL,
    ENV_MQTT_KEEP_ALIVE_INTERVAL,
    ENV_MQTT_QUEUE_DIR,
    ENV_MQTT_QUEUE_LIMIT,
]