import os
# Assuming COMMENT_KEY and ENABLE_KEY are defined elsewhere, possibly in a constants module
# For example:
# from config.constants import COMMENT_KEY, ENABLE_KEY

COMMENT_KEY = "comment"
ENABLE_KEY = "enable"


# Webhook Keys
WEBHOOK_ENDPOINT = "endpoint"
WEBHOOK_AUTH_TOKEN = "auth_token"
WEBHOOK_QUEUE_LIMIT = "queue_limit"
WEBHOOK_QUEUE_DIR = "queue_dir"
WEBHOOK_CLIENT_CERT = "client_cert"
WEBHOOK_CLIENT_KEY = "client_key"

# A list of all valid configuration keys for a webhook target.
NOTIFY_WEBHOOK_KEYS = [
    ENABLE_KEY,  # "enable" is a common key
    WEBHOOK_ENDPOINT,
    WEBHOOK_AUTH_TOKEN,
    WEBHOOK_QUEUE_LIMIT,
    WEBHOOK_QUEUE_DIR,
    WEBHOOK_CLIENT_CERT,
    WEBHOOK_CLIENT_KEY,
    COMMENT_KEY,
]

# Webhook Environment Variables
ENV_WEBHOOK_ENABLE = "RUSTFS_NOTIFY_WEBHOOK_ENABLE"
ENV_WEBHOOK_ENDPOINT = "RUSTFS_NOTIFY_WEBHOOK_ENDPOINT"
ENV_WEBHOOK_AUTH_TOKEN = "RUSTFS_NOTIFY_WEBHOOK_AUTH_TOKEN"
ENV_WEBHOOK_QUEUE_LIMIT = "RUSTFS_NOTIFY_WEBHOOK_QUEUE_LIMIT"
ENV_WEBHOOK_QUEUE_DIR = "RUSTFS_NOTIFY_WEBHOOK_QUEUE_DIR"
ENV_WEBHOOK_CLIENT_CERT = "RUSTFS_NOTIFY_WEBHOOK_CLIENT_CERT"
ENV_WEBHOOK_CLIENT_KEY = "RUSTFS_NOTIFY_WEBHOOK_CLIENT_KEY"

ENV_NOTIFY_WEBHOOK_KEYS = [
    ENV_WEBHOOK_ENABLE,
    ENV_WEBHOOK_ENDPOINT,
    ENV_WEBHOOK_AUTH_TOKEN,
    ENV_WEBHOOK_QUEUE_LIMIT,
    ENV_WEBHOOK_QUEUE_DIR,
    ENV_WEBHOOK_CLIENT_CERT,
    ENV_WEBHOOK_CLIENT_KEY,
]