"""File sink environment keys and defaults for observability."""

# Environment variable keys
ENV_SINKS_FILE_PATH = "RUSTFS_SINKS_FILE_PATH"
ENV_SINKS_FILE_BUFFER_SIZE = "RUSTFS_SINKS_FILE_BUFFER_SIZE"
ENV_SINKS_FILE_FLUSH_INTERVAL_MS = "RUSTFS_SINKS_FILE_FLUSH_INTERVAL_MS"
ENV_SINKS_FILE_FLUSH_THRESHOLD = "RUSTFS_SINKS_FILE_FLUSH_THRESHOLD"

# Defaults
DEFAULT_SINKS_FILE_BUFFER_SIZE = 8192
DEFAULT_SINKS_FILE_FLUSH_INTERVAL_MS = 1000
DEFAULT_SINKS_FILE_FLUSH_THRESHOLD = 100