"""Kafka sink environment keys and defaults for observability."""

# Environment variable keys
ENV_SINKS_KAFKA_BROKERS = "RUSTFS_SINKS_KAFKA_BROKERS"
ENV_SINKS_KAFKA_TOPIC = "RUSTFS_SINKS_KAFKA_TOPIC"
ENV_SINKS_KAFKA_BATCH_SIZE = "RUSTFS_SINKS_KAFKA_BATCH_SIZE"
ENV_SINKS_KAFKA_BATCH_TIMEOUT_MS = "RUSTFS_SINKS_KAFKA_BATCH_TIMEOUT_MS"

# Defaults
DEFAULT_SINKS_KAFKA_BROKERS = "localhost:9092"
DEFAULT_SINKS_KAFKA_TOPIC = "rustfs-sinks"
DEFAULT_SINKS_KAFKA_BATCH_SIZE = 100
DEFAULT_SINKS_KAFKA_BATCH_TIMEOUT_MS = 1000