"""Webhook sink environment keys and defaults for observability."""

# Environment variable keys
ENV_SINKS_WEBHOOK_ENDPOINT = "RUSTFS_SINKS_WEBHOOK_ENDPOINT"
ENV_SINKS_WEBHOOK_AUTH_TOKEN = "RUSTFS_SINKS_WEBHOOK_AUTH_TOKEN"
ENV_SINKS_WEBHOOK_MAX_RETRIES = "RUSTFS_SINKS_WEBHOOK_MAX_RETRIES"
ENV_SINKS_WEBHOOK_RETRY_DELAY_MS = "RUSTFS_SINKS_WEBHOOK_RETRY_DELAY_MS"

# Defaults
DEFAULT_SINKS_WEBHOOK_ENDPOINT = "http://localhost:8080"
DEFAULT_SINKS_WEBHOOK_AUTH_TOKEN = ""
DEFAULT_SINKS_WEBHOOK_MAX_RETRIES = 3
DEFAULT_SINKS_WEBHOOK_RETRY_DELAY_MS = 100